openapi: 3.0.0
info:
  title: Moonlay Python API
  version: 1.0.0
  description: API for managing cities
servers:
  - url: https://api.moonlay.com
    description: Production server
  - url: http://localhost:8000
    description: Development server
paths:
  /:
    get:
      summary: Home
      description: Returns a welcome message
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  message:
                    type: string
                  data:
                    type: array
                    items:
                      type: object
  /cities:
    get:
      summary: Get all cities
      description: Retrieves a list of all cities
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  message:
                    type: string
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                        name:
                          type: string
                        country:
                          type: string
    post:
      summary: Create a new city
      description: Creates a new city
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                country:
                  type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  message:
                    type: string
                  data:
                    type: object
                    properties:
                      id:
                        type: integer
                      name:
                        type: string
                      country:
                        type: string
  /cities/{city_id}:
    get:
      summary: Get a city
      description: Retrieves a specific city by ID
      parameters:
        - in: path
          name: city_id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  message:
                    type: string
                  data:
                    type: object
                    properties:
                      id:
                        type: integer
                      name:
                        type: string
                      country:
                        type: string
    put:
      summary: Update a city
      description: Updates a specific city by ID
      parameters:
        - in: path
          name: city_id
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                country:
                  type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  message:
                    type: string
                  data:
                    type: object
                    properties:
                      id:
                        type: integer
                      name:
                        type: string
                      country:
                        type: string
    delete:
      summary: Delete a city
      description: Deletes a specific city by ID
      parameters:
        - in: path
          name: city_id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  message:
                    type: string
                  data:
                    type: array
                    items:
                      type: object